scrape_configs:
  - job_name: 'Route optimiser actuator scrapper'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:5000']
        labels:
          application: 'route-optimiser-service'